CREATE TABLE char_data_types (
	char_column CHAR(10),
	varchar_column VARCHAR(10),
	text_column TEXT
);

INSERT INTO char_data_types
VALUES 
	('abc', 'abc', 'abc'),
	('defghi', 'defghi', 'defghi');

COPY char_data_types TO 'C:\postgres_exports\typetest.txt'
--\copy char_data_types TO 'C:\postgres_exports\typetest.txt'
WITH (FORMAT CSV, HEADER, DELIMITER '|');

/*Understandin numbers

Integers: smallint, integer, bigint (Consumes the most storage)
autoincrementing with serial: smallserial, serial, bigserial*/

CREATE TABLE people (
	id SERIAL,
	person_name VARCHAR(100)
);

/*IDENTITY: The standard SQL implementation for auto-incrementing integers
	How to use it:
		GENERATED ALWAYS AS IDENTITY: User cannot insert a value into id column without manually overriding that setting
		GENERATED BY DEFAULT AS IDENTITY: Fill the column with auto-incremented value by default if the user does not supply onw
										  It allow for duplicate values -> Problematic for creating key columns.

*/

CREATE TABLE people (
	id INTEGER GENERATED ALWAYS AS IDENTITY,
	person_name VARCHAR(100)
);

/* Fixed-Point Numbers -> arbitrary precision type

NUMERIC(precision, scale): Number of digits to the left and right of the decimal point

   Understaing Floating-Point Types
REAL and DOUBLE PRECISION
*/